# Generated by Django 3.0.2 on 2021-06-03 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='dept_fax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('reply_status', models.IntegerField(default=0)),
                ('seen', models.IntegerField(default=0)),
                ('notified', models.IntegerField(default=0)),
                ('last_notified', models.DateTimeField(default=django.utils.timezone.now)),
                ('seen_by', models.CharField(default='', max_length=264)),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faxat.dept')),
            ],
        ),
        migrations.CreateModel(
            name='fax',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sader', models.IntegerField(default=0)),
                ('sader_edara', models.IntegerField(default=0)),
                ('title', models.TextField()),
                ('url', models.FileField(upload_to='faxat_data/faxes/%Y/%m/%d')),
                ('replay_to_edara', models.FileField(blank=True, null=True, upload_to='faxat_data/replay_to_edara/%Y/%m/%d')),
                ('comments', models.TextField(default=' ')),
                ('replay_dept', models.TextField(default=' ')),
                ('send_dept', models.TextField(default=' ')),
                ('come_from_dept', models.TextField(default=' ')),
                ('manager_comments', models.TextField(default=' ')),
                ('v_manager_comments', models.TextField(default=' ')),
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('approved', models.IntegerField(default=0)),
                ('approved_id', models.TextField(default=' ')),
                ('date_aproved', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('fax_type', models.IntegerField(default=0)),
                ('notified', models.IntegerField(default=0)),
                ('is_removable', models.IntegerField(default=0)),
                ('last_notified_m', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_notified_vm', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LoggedUserNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='fax_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.IntegerField(default=0)),
                ('dep_comment', models.TextField(default='')),
                ('dep_document', models.FileField(null=True, upload_to='faxat_data/comments/%Y/%m/%d')),
                ('writer', models.CharField(max_length=264, null=True)),
                ('user_type', models.CharField(max_length=264, null=True)),
                ('date', models.DateTimeField()),
                ('notified', models.IntegerField(default=0)),
                ('last_notified', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_status', models.IntegerField(default=10)),
                ('seen_by', models.CharField(default='', max_length=264)),
                ('dept_fax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faxat.dept_fax')),
            ],
        ),
        migrations.AddField(
            model_name='dept_fax',
            name='fax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faxat.fax'),
        ),
        migrations.AddField(
            model_name='dept',
            name='fax',
            field=models.ManyToManyField(blank=True, through='faxat.dept_fax', to='faxat.fax'),
        ),
    ]
